# Generated by Django 5.1.7 on 2025-03-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
