# Generated by Django 5.1.7 on 2025-08-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_databases_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='databases',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
